import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "URL Shortner",
  description: "Generated by Manash Anand",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="min-h-screen container">
        
        {children}
      </main>
      <div className="p-10 text-center bg-gray-800 mt-10">
        Made with 💗 by Manash Anand
      </div>
        </body>
    </html>
  );
}
